### PR TITLE
Fix runtime error when installing with pnpm

### LINKED ISSUE #199: `no such file or directory, open 'node_modules/@vtbag/inspection-chamber/lib/index.js'` when installing with pnpm
### Describe the Bug

Hi Martin,

when installing `astro-vtbot` with pnpm an error is thrown at runtime. It appears that this line
https://github.com/martrapp/astro-vtbot/blob/400371faba356a7e71a1f21da6b71debd00c46e8/integration/astro-inspection-chamber.js.ts#L3
is the culprit, because it's using a file read from `node_modules` directly, which doesn't work if the structure of `node_modules` is different than expected. Pnpm installs peer dependencies into a different directory, so the path in the error message doesn't exist. If `pnpm install` is called with the `--shamefully-hoist` option the error disappears, since it matches npm's file structure, but usage of the option is not encouraged and it shouldn't be necessary.

I've changed the line above to use a raw vite import statement like so
```ts
import inspectionChamber from "@vtbag/inspection-chamber/lib/index.js?raw";
```
which does seem to fix the problem entirely (even the Astro toolbar integration seems to be working)

Happy to send you a PR to fix this, but I would need a bit of guidance on how to test if it actually works and doesn't break anything else

### What's the expected result?

pnpm should be supported without the `--shamefully-hoist` flag

### Link to Minimal Reproducible Example

https://stackblitz.com/~/github.com/Trombach/vtbot-import

### Participation

- [X] I am willing to submit a pull request for this issue.

### PR DESCRIPTION
**Pull request by Trombach**
### Description

 - changes `readFileSync` to `raw` vite import to prevent error when installing astro-vtbot with pnpm
 - fixes #199 

### Tests

- TBD

@martrapp thanks for helping me with testing :)

### Docs & Examples

- just bugfix

### CODE REVIEW

**Comment by martrapp** [comment]
Hi Lukas, great, your change looks very good to me.
Thank you so much for taking care!

I'm happy to do the further testing. I'm already convinced that this change is a real improvement for the stability and maintainability of the code!

**Comment by Trombach** [comment]
That's great to hear! As I said before, let me know if you need any help testing this.

File: integration/astro-inspection-chamber.js.ts [hunk 1]
```diff
@@ -1,6 +1,4 @@
-import { readFileSync } from 'node:fs';
-
-const inspectionChamber = readFileSync('node_modules/@vtbag/inspection-chamber/lib/index.js');
+import inspectionChamber from '@vtbag/inspection-chamber/lib/index.js?raw';
```
Comment (martrapp) [inline integration/astro-inspection-chamber.js.ts:1]:
```suggestion
import "astro/client";
import inspectionChamber from "@vtbag/inspection-chamber?raw";
```

**Review by martrapp — COMMENTED** [review]
This would be even more elegant. What do you think?

File: integration/astro-inspection-chamber.js.ts (hunk 1 above)
Comment (Trombach) [reply integration/astro-inspection-chamber.js.ts:1]: Yes! That's great.

Out of curiosity: when I made the change I noticed that the import statement had an error, stating that it couldn't find the module (even though it worked fine). Importing `astro/client` seems to get rid of this and the module can be found. Do you know why that is the case here?

Comment (martrapp) [reply integration/astro-inspection-chamber.js.ts]: There is a lot stuff in that file, but we need just those 4 lines:
```
declare module '*?raw' {
	const src: string;
	export default src;
}
```

Comment (martrapp) [reply integration/astro-inspection-chamber.js.ts]: However, this only seems to have mask the error message you have seen. In fact, the .d.ts declarations were also missing in @vtbag/inspection-chamber (Thus it was not recognized as a module). They will come with the next release.

**Review by martrapp — APPROVED** [review]
LGTM
